spring:
  application:
    name: LeonardoOverflow

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/leonardo_overflow?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: 'root'
    password: 'toor'
    driver-class-name: com.mysql.cj.jdbc.Driver

#jwt
jwt:
  secret: securityOopsie
  expiration: 86400000

